import { Metadata } from 'next';

export const metadata: Metadata = {
  metadataBase: new URL('https://certestic.com'),
  title: 'Certestic | AI-Powered IT Certification Training for AWS, Azure, GCP & More | Free Beta',
  description:
    'Master AWS, Azure, GCP, and 100+ IT certifications with AI-powered adaptive practice exams. Get personalized study plans, identify knowledge gaps, and pass certifications faster with realistic exam simulations. Free beta access available now.',
  keywords: [
    'Certestic',
    'AWS certification practice exams',
    'Azure certification training',
    'GCP practice tests',
    'CompTIA Security+ exam prep',
    'IT certification AI training',
    'cloud certification practice',
    'AWS Solutions Architect practice',
    'Azure Administrator exam prep',
    'Google Cloud certification study',
    'Cisco CCNA practice exams',
    'cybersecurity certification prep',
    'VMware certification training',
    'AI-powered certification study',
    'adaptive learning technology',
    'personalized exam preparation',
    'realistic exam simulation',
    'IT professional development',
    'online certification training',
    'certification success platform',
    'knowledge gap identification',
    'self-paced exam prep',
    'interactive practice tests',
    'certification study platform',
    'IT career advancement',
    'machine learning education',
    'free beta certification training',
    'exam readiness assessment',
    'intelligent study paths',
    'certification mastery platform',
  ].join(', '),
  authors: [{ name: 'Certestic Team' }],
  creator: 'Certestic',
  publisher: 'Certestic',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    title: 'Certestic | Master AWS, Azure, GCP & IT Certifications with AI-Powered Practice Exams',
    description:
      'Personalized AI-powered practice exams for 100+ IT certifications. Adaptive learning creates smart study plans that identify gaps and accelerate your path to certification success.',
    type: 'website',
    locale: 'en_US',
    url: '/',
    siteName: 'Certestic',
    images: [
      {
        url: 'https://certestic.com/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Certestic - AI-Powered IT Certification Training Platform',
        type: 'image/png',
      },
      {
        url: 'https://certestic.com/og-image-square.png',
        width: 800,
        height: 800,
        alt: 'Certestic Logo',
        type: 'image/png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Certestic | Master IT Certifications with AI-Powered Practice Exams',
    description:
      'Pass AWS, Azure, GCP & 100+ IT certifications faster with personalized AI-powered practice exams. Adaptive learning identifies gaps and creates smart study paths.',
    creator: '@Certestic',
    site: '@Certestic',
    images: [
      {
        url: 'https://certestic.com/og-image.png',
        alt: 'Certestic - AI-Powered Certification Training',
      },
    ],
  },
  alternates: {
    canonical: 'https://certestic.com',
  },
  category: 'Education',
  applicationName: 'Certestic',
  referrer: 'origin-when-cross-origin',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Certestic',
  },
};
