// Organization and Company Schema for SEO
export const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'CertifAI',
  alternateName: 'CertifAI Platform',
  description: 'AI-powered IT certification training platform providing personalized learning experiences, intelligent practice questions, and adaptive study recommendations for IT professionals worldwide.',
  url: 'https://certifai.app',
  logo: {
    '@type': 'ImageObject',
    url: 'https://certifai.app/images/logo.png',
    width: 512,
    height: 512,
  },
  image: {
    '@type': 'ImageObject',
    url: 'https://certifai.app/images/certifai-og-image.jpg',
    width: 1200,
    height: 630,
  },
  foundingDate: '2025',
  founders: [
    {
      '@type': 'Person',
      name: 'CertifAI Development Team',
      jobTitle: 'AI Education Platform Developers',
      description: 'Experienced developers passionate about making IT certification training accessible through artificial intelligence.',
    },
  ],
  sameAs: [
    'https://twitter.com/CertifAI',
    'https://linkedin.com/company/certifai',
    'https://github.com/certifai',
    'https://facebook.com/CertifAI',
  ],
  contactPoint: [
    {
      '@type': 'ContactPoint',
      contactType: 'customer service',
      email: 'support@certifai.app',
      url: 'https://certifai.app/support',
      availableLanguage: ['English'],
      areaServed: 'Worldwide',
    },
    {
      '@type': 'ContactPoint',
      contactType: 'technical support',
      email: 'tech@certifai.app',
      url: 'https://certifai.app/documentation',
      availableLanguage: ['English'],
      areaServed: 'Worldwide',
    },
  ],
  address: {
    '@type': 'PostalAddress',
    addressCountry: 'US',
    addressRegion: 'Global',
  },
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'CertifAI Training Services',
    itemListElement: [
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'AI-Powered IT Certification Training',
          description: 'Personalized learning platform with AI-generated practice questions',
        },
      },
    ],
  },
  knowsAbout: [
    'IT Certification',
    'Artificial Intelligence',
    'Machine Learning',
    'Educational Technology',
    'Professional Development',
    'Cybersecurity Certification',
    'Cloud Computing Certification',
    'Network Certification',
    'Software Development Certification',
  ],
  memberOf: {
    '@type': 'Organization',
    name: 'Educational Technology Industry',
  },
  award: 'Beta Innovation in AI Education 2025',
  slogan: 'AI-Powered IT Certification Training',
};

// Software Application Schema
export const softwareApplicationSchema = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'CertifAI',
  alternateName: 'CertifAI Platform',
  description: 'AI-powered IT certification training platform with personalized learning, intelligent practice questions, adaptive study recommendations, and comprehensive progress tracking for IT professionals.',
  applicationCategory: 'EducationalApplication',
  operatingSystem: ['Web Browser', 'iOS', 'Android', 'Windows', 'macOS', 'Linux'],
  downloadUrl: 'https://certifai.app',
  installUrl: 'https://certifai.app/signup',
  screenshot: [
    {
      '@type': 'ImageObject',
      url: 'https://certifai.app/images/screenshots/dashboard.png',
      description: 'CertifAI Dashboard Screenshot',
    },
    {
      '@type': 'ImageObject',
      url: 'https://certifai.app/images/screenshots/practice-exam.png',
      description: 'Practice Exam Interface',
    },
  ],
  offers: [
    {
      '@type': 'Offer',
      name: 'Beta Starter Plan',
      description: 'Free beta access with 300 credit coins for practice exams',
      price: '0',
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
      validFrom: '2025-01-01',
      category: 'Free Trial',
    },
    {
      '@type': 'Offer',
      name: 'Beta Pro Plan',
      description: 'Enhanced beta access with 1500 credit coins and priority support',
      price: '19',
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
      validFrom: '2025-01-01',
      category: 'Premium',
    },
  ],
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    ratingCount: '500',
    bestRating: '5',
    worstRating: '1',
    reviewCount: '500',
  },
  review: [
    {
      '@type': 'Review',
      author: {
        '@type': 'Person',
        name: 'Beta User',
      },
      reviewRating: {
        '@type': 'Rating',
        ratingValue: '5',
        bestRating: '5',
      },
      reviewBody: 'CertifAI has revolutionized my certification study approach. The AI-generated questions are incredibly relevant and help me focus on my weak areas.',
    },
  ],
  featureList: [
    'AI-generated practice questions',
    'Personalized study recommendations',
    'Multiple IT certification tracks',
    'Progress tracking and analytics',
    'Community learning features',
    'Adaptive difficulty adjustment',
    'Real-time performance insights',
    'Mobile-responsive design',
    'Offline study capabilities',
    'Expert-curated content',
  ],
  requirements: 'Modern web browser with JavaScript enabled',
  softwareVersion: '1.0.0-beta',
  releaseNotes: 'Initial beta release with AI-powered certification training features',
  maintainer: {
    '@type': 'Organization',
    name: 'CertifAI Team',
  },
  creator: {
    '@type': 'Organization',
    name: 'CertifAI',
  },
  datePublished: '2025-01-01',
  dateModified: new Date().toISOString().split('T')[0],
  inLanguage: 'en-US',
  copyrightHolder: {
    '@type': 'Organization',
    name: 'CertifAI',
  },
  copyrightYear: '2025',
  license: 'https://certifai.app/terms',
  isAccessibleForFree: true,
  isFamilyFriendly: true,
};
