name: Deploy Next.js App to Firebase App Hosting

on:
  push:
    branches:
      - main # Or your production branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install # Or yarn install or pnpm install

      - name: Build Next.js app
        run: npm run build

      - name: Set up Firebase CLI
        run: |
          npm install -g firebase-tools
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > /tmp/serviceAccountKey.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/serviceAccountKey.json

      - name: Deploy to Firebase App Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Clean up temporary credentials file
        run: rm -f /tmp/serviceAccountKey.json
        if: success() || failure()
